language: python
python:
- '2.7'
- '3.6'
install:
- pip install tox-travis
script:
- tox
- bash <(curl -s https://codecov.io/bash) -f .tox/py3-testcoverage.xml -f .tox/py27-testcoverage.xml
deploy:
  provider: pypi
  user: adtran-automation
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: ADTRAN/netconf_client
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  password:
    secure: AnE/Rjtn0X0yZ3xH1DajiBS58nLRHOGycZ+2vssZbz2pu/UJSJs8aWPN0k9QUFjT4MiU19j1wiW7NxUXY+LK+Gbcy5uFdeP9/VScTtZIX0c4JAuWSkLTgfNRx16NZmG1fUwMfeh4BnzSzCniZefQO19aAoZiPuJUo/EWQraCZlc7FwFVU6Gx00TXTPfxegjUI5pTlKHzZc+fxraL8kfHDvg4FgZmie6Su25CHkPYZZ98VM9ao7uVdlW8LksN2XA8cQRChlG4G8HYeROZmBhAcCt9h+F19z3xL7FS2Xu+Atemxfkb9WhgSRpEvpgcXOOPdEnloAUYURPUY4rO0iXxCSIiNPY4XivmP8dRUP+WPLBUvWYWsZvk2RPW0WimWSUvQfcZHVfwriutpwBjJx00NZujJ4qkEdaFN3UAYUC05hL8YsCiG9GvtW86e86csWCvt1zQpiJWvahkk0njvI3MZREX/X5wh1Hh9IqoWjCqyoW4yRfVvYiRaM8Ll7/IB7XOAInFglHPiPbzogSqOEuSIrsI3/WS5zaVm81XjxpQEqGqQyACqpE/lAT666i0n0KrUQ+L0tzVbt3pwbTNpmyR/C1I0o7Q1BzhEpZdUKAxPOX61tnEz0EctWTvyFnqlU1u9r6jR8S8S67EGZX4XqSPBIQCjZoPUz70Nackaqg9JtM=
